---
---
# TUTORIAL 2: INTRODUCTION TO PYTHON

Python is a popular, general-purpose programming language designed to be easy to read and simple to write. It's become the undisputed industry-standard when it comes to data science and AI, so we will be using it extensively in this course. By the end of the course you will all be fluent in Python. 

Today we'll start with a very basic introduction: how to use Python as a calculator and how to read in data.

---
---

## 🧮 Basic Mathematical Operations

Unlike above, we now want our cells to be "code" cells. Otherwise, the notebook will not interpret the Python code correctly when the cell is run. [Exercise: what happens if you change one of the cell types below?]

Below is a code cell carrying out a very basic calculation.

In [2]:
# Addition
3 + 2

5

Notice:

* Below the code cell is a result; the result of running the cell's code. We call this the code's **output**. 
* In the code cell there is some green text preceded by the hash symbol `#`. This is called a **comment** and programmers include these to explain what a piece of code is doing. Note that when a code cell is run, comments are not treated like code--they're ignored. [Exercise: what happens if you delete the `#` symbol and try to run the cell? What happens if you delete the entire comment?]

Let's carry on and see how to do other basical mathematical operations.

In [3]:
# Subtraction
3 - 2

1

In [4]:
# Multiplication
3 * 2

6

In [5]:
# Division
3 / 2

1.5

In [6]:
# Remainder
3 % 2

1

In [7]:
# Exponentiation
3 ** 2

9

In [8]:
# Square root
3 ** 0.5

1.7320508075688772

In [9]:
# BEDMAS
(3 + 2) ** 2 / (2 * 3)

4.166666666666667

---
### 🔍 Check Your Understanding
Perform each of the requested calculations below, using the operations you've learned above.

1. Perform the following calculation: $$\left(\frac{100}{4}\right) \times 2 + |5 - 15|$$

2. Perform the following calculation: $$\sqrt{\frac{(10-7)^2}{3\times(1+2)}}$$

3. Calculate the length ($x$) of the hypotenuse of this right angle triangle:

<div style="text-align: center;">
  <img src="https://raw.githubusercontent.com/ntstevens/DATSC101/59298f312bb0f45183441edf648e4ad3cca240c4/images/pythagoras.svg" alt="pythagoras example" width = "300" />
</div>

---
---
## 📚 Libraries and Functions

We've just about exhausted the mathematical operations "base" Python is capable of. When we need to perform a more advanced calculation, we're going to need to import a **library**.

What is a library?
* 🧙 Think of yourself as a wizard capable of many advanced spells, but you need your spellbook in order to do them. 
* 🧑‍🍳 Think of yourself as a chef capable of many advanced recipes, but you need your cookbook in order to do them.
* 🧑‍🔬 Data scientists are similar. We can apply many advanced *functions*, but we need access to the library containing those functions in order to use them.

What is a function?

* A function is a reusable, self-contained block of code designed to perform a specific task.

Today we'll work with a library called `numpy` (pronounced *numb-pie*), which is commonly used for scientific computing in Python. We'll use is to perform some mathametical calculations available to us via functions.

Let's revisit the square root calculation we performed above:

In [10]:
3 ** 0.5

1.7320508075688772

There is a dedicated function for this in `numpy` called `sqrt()`. In order to use it, we need to import the library:

In [11]:
import numpy

That was easy. Now we have access to any and all functions stored in the `numpy` library. Let's test out the `sqrt()` function.

In [12]:
numpy.sqrt(3)

1.7320508075688772

Success! And this agrees with the result above. 

Notice the syntax we used to run the `sqrt()` function. This is an example of the following broader principle:

<div style="text-align: center;">
  <img src="https://raw.githubusercontent.com/ntstevens/DATSC101/59298f312bb0f45183441edf648e4ad3cca240c4/images/function_example.svg" alt="function example" />
</div>

Let's explore some other functions in `numpy`.

In [13]:
# Round
numpy.round(4.7)

5.0

In [14]:
# Absolute value
numpy.abs(-3)

3

In [15]:
# Exponents
numpy.power(2,3)

8

But writing out the library name is inefficient and annoying! We can simplify things by importing `numpy` under a shorter **alias**.

In [16]:
import numpy as np

Now, anytime we need to refer to `numpy` we can do so using the alias `np`.

In [17]:
np.sqrt(3)

1.7320508075688772

In [18]:
np.round(4.7)

5.0

In [19]:
np.abs(-3)

3

In [20]:
np.power(2,3)

8

`numpy` contains many functions and vast capability. We'll return to this library often throughout the course as we expand our toolboxes. [Click here](https://numpy.org/) if you want to browse the `numpy` documentation to see what else it can do.

---
### 🔍 Check Your Understanding
Perform each of the calculations we did above, but this time making use of `numpy` functions.

1. Perform the following calculation: $$\left(\frac{100}{4}\right) \times 2 + |5 - 15|$$

2. Perform the following calculation: $$\sqrt{\frac{(10-7)^2}{3\times(1+2)}}$$

3. Calculate the length ($x$) of the hypotenuse of this right angle triangle:

<div style="text-align: center;">
  <img src="https://raw.githubusercontent.com/ntstevens/DATSC101/59298f312bb0f45183441edf648e4ad3cca240c4/images/pythagoras.svg" alt="pythagoras example" width = "300" />
</div>

---
---
## 💽 Loading Data

Data scientists analyze data, and they do so with Python. So, the first step in any data analysis is to load the data into your working environment so that Python has access to it. We do this by _loading_ or _reading in_ the data.

---

### Tabular Data

Data comes in a variety of shapes, sizes, and formats, but we will begin with the most basic data structure: **tables**. Tabular data is what you think of if you imagine information stored in spreadsheets. It's rectangular in shape, with **rows** and **columns**. The image below provides an example of tabular data containing information about movies. 

<div style="text-align: center;">
<img src="https://raw.githubusercontent.com/ntstevens/DATSC101/refs/heads/main/images/movie_info.png" alt="movie info" width="800"/>
</div>


The top _row_ of this dataset is a **header** row which provides the _column_ names. We can see that the columns represent movie attributes.

Every other row represents a different movie, and the columns contain specific characteristics for the respective movie. In particular, we have information on:

* `names`: the movie name
* `date_x`: the release of the movie
* `score`: the IMBD score for the movie (multiplied by 10)
* `genre`: the genre(s) of the movie
* `overview`: a summary of the movie
* `crew`: notable cast in the movie
* `orig_title`: the original tile of the movie (often but not always the same as `names`)

**In general, tabular data is structured as follows:**

* Rows represent the objects we study. We call these **observations**.
* Columns represent characteristics of those objects. We call these **variables**.
* A **cell** contains the value of a particular variable for a particular observation.

---
### Introduction to `pandas`

So, if we have a dataset like this, stored in a spreadsheet, how do we load it? With pandas! 

No, not these _pandas_: 🐼

We use `pandas`. It's another library like `numpy` which contains helpful functions. Here we will illustrate a particularly useful function for reading in tabular data:

* `read_csv` which reads in tabular data stored in a `.csv` file

#### Importing and using `pandas`

Let's import `pandas` and start to get familiar with these functions. Note that we'll important `pandas` with the commonly used alias `pd`.

In [21]:
import pandas as pd

The dataset pictured above is stored in a `.csv` file called `imdb_movie_info.csv`. With that file in hand, we can read it in with the function `read_csv`. But first, recall the syntax needed to use a function contained in a library:

```Python
library.function("argument")
```

So, we'll need to do something like: 

```Python
pd.read_csv(...)
```

But obviously we need to replace `...` with something. _But what?_

#### Accessing Documentation

Now is a good time to illustrate the use of **documenation**; a function's documentation tells you how to use the function. It explains all of the relevant inputs and outputs. We can access it with the `help` function or by typing the question mark `?` ahead of a function name. Try it below:

As we can see, `pd.read_csv` takes many inputs. While we'll explore many of them later in the course, today we'll focus on the main one. The first one:

```
filepath_or_buffer : str, path object or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
    expected. A local file could be: file://localhost/path/to/table.csv.
```

So, if we pass the filepath as a string, `pd.read_csv` will 

1. know what we're looking for,
2. know where to find it, and 
3. read it in. 

In general: we find the `filepath` for the data file, and then run:

```Python
pd.read_csv("filepath")
```

Below we consider some special cases and note the difference between _absolute_ and _relative_ filepaths.

#### Loading data from the same folder as your notebook

<div style="text-align: center;">
  <img src="https://raw.githubusercontent.com/ntstevens/DATSC101/51e70d2a129b37c095aee72db6589ccd4f42626c/images/filepath_data_same_folder.svg" alt="filepath_same_folder" width = "600" />
</div>

To determine the `filepath` for our data, we need to trace it through the filesytem. The schematic above shows us that the data (the `.csv` file at the bottom) lives in the "Tutorials" folder. The corresponding file path is: `/Users/NSTEVENS/Teaching/DATSC101/Tutorials/imdb_movie_info.csv`.

This is called an **absolute path** because it gives the location of the file with respect to the computer’s filesystem root folder. But absolute paths should be avoided, if possible, because they rely on knowing the (potentially complicated) path from the root folder.

Instead, we can use a **relative path**, which gives the location of the file with respect to where we're currently working. That is, relative to the location of the Jupyter notebook. 

As the schematic indicates, the data lives in the _same folder_ as the Jupyter notebook. In this case, the relative path is easy. It's just the filename: `imdb_movie_info.csv`.

Let's call `pd.read_csv` using this simple filepath:

In [22]:
pd.read_csv("imdb_movie_info.csv")

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
0,Creed III,03/02/2023,73,"Drama, Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",Creed III,Released,English,75000000.0,2.716167e+08,AU
1,Avatar: The Way of Water,12/15/2022,78,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU
2,The Super Mario Bros. Movie,04/05/2023,76,"Animation, Adventure, Family, Fantasy, Comedy","While working underground to fix a water main,...","Chris Pratt, Mario (voice), Anya Taylor-Joy, P...",The Super Mario Bros. Movie,Released,English,100000000.0,7.244590e+08,AU
3,Mummies,01/05/2023,70,"Animation, Comedy, Family, Adventure, Fantasy","Through a series of unfortunate events, three ...","Óscar Barberán, Thut (voice), Ana Esther Albor...",Momias,Released,"Spanish, Castilian",12300000.0,3.420000e+07,AU
4,Supercell,03/17/2023,61,Action,Good-hearted teenager William always lived in ...,"Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...",Supercell,Released,English,77000000.0,3.409420e+08,US
...,...,...,...,...,...,...,...,...,...,...,...,...
10173,20th Century Women,12/28/2016,73,Drama,"In 1979 Santa Barbara, California, Dorothea Fi...","Annette Bening, Dorothea Fields, Lucas Jade Zu...",20th Century Women,Released,English,7000000.0,9.353729e+06,US
10174,Delta Force 2: The Colombian Connection,08/24/1990,54,Action,When DEA agents are taken captive by a ruthles...,"Chuck Norris, Col. Scott McCoy, Billy Drago, R...",Delta Force 2: The Colombian Connection,Released,English,9145817.8,6.698361e+06,US
10175,The Russia House,12/21/1990,61,"Drama, Thriller, Romance","Barley Scott Blair, a Lisbon-based editor of R...","Sean Connery, Bartholomew 'Barley' Scott Blair...",The Russia House,Released,English,21800000.0,2.299799e+07,US
10176,Darkman II: The Return of Durant,07/11/1995,55,"Action, Adventure, Science Fiction, Thriller, ...",Darkman and Durant return and they hate each o...,"Larry Drake, Robert G. Durant, Arnold Vosloo, ...",Darkman II: The Return of Durant,Released,English,116000000.0,4.756613e+08,US
10177,The Swan Princess: A Royal Wedding,07/20/2020,70,"Animation, Family, Fantasy",Princess Odette and Prince Derek are going to ...,"Nina Herzog, Princess Odette (voice), Yuri Low...",The Swan Princess: A Royal Wedding,Released,English,92400000.0,5.394018e+08,GB

#### Loading data from a different folder than your notebook

**Case 1: Data is "below" your Jupyter Notebook"**
<div style="text-align: center;">
  <img src="https://raw.githubusercontent.com/ntstevens/DATSC101/7039ae41433c56ae722f8da31f1e5adb8a7ecb05/images/filepath_data_diff_folder2.svg" alt="filepath_diff_folder2" width = "400" />
</div>

When the data file is in a folder that is itself contained within the folder containing the Jupyter notebook (pictured above), the relative path is simply the path starting from the Jupyter notebook's location: `Data/imdb_movie_info.csv`.

**Case 2: Data is "above" your Jupyter Notebook"**
<div style="text-align: center;">
  <img src="https://raw.githubusercontent.com/ntstevens/DATSC101/51e70d2a129b37c095aee72db6589ccd4f42626c/images/filepath_data_diff_folder.svg" alt="filepath_diff_folder1" width = "400" />
</div>

If instead, the data file is in a folder "above" the Jupyter notebook, we need to traverse backward through the filesystem. We do this with two dots `..`. This moves us to the previous folder. So, to get from the Jupyter notebook to the data file in the schematic above, the relative path is `../Data/imdb_movie_info.csv`.

My filesystem in JupyterHub is organized like Case 1. So we use that filepath as follows:

In [25]:
pd.read_csv("Data/imdb_movie_info.csv")

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
0,Creed III,03/02/2023,73,"Drama, Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",Creed III,Released,English,75000000.0,2.716167e+08,AU
1,Avatar: The Way of Water,12/15/2022,78,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU
2,The Super Mario Bros. Movie,04/05/2023,76,"Animation, Adventure, Family, Fantasy, Comedy","While working underground to fix a water main,...","Chris Pratt, Mario (voice), Anya Taylor-Joy, P...",The Super Mario Bros. Movie,Released,English,100000000.0,7.244590e+08,AU
3,Mummies,01/05/2023,70,"Animation, Comedy, Family, Adventure, Fantasy","Through a series of unfortunate events, three ...","Óscar Barberán, Thut (voice), Ana Esther Albor...",Momias,Released,"Spanish, Castilian",12300000.0,3.420000e+07,AU
4,Supercell,03/17/2023,61,Action,Good-hearted teenager William always lived in ...,"Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...",Supercell,Released,English,77000000.0,3.409420e+08,US
...,...,...,...,...,...,...,...,...,...,...,...,...
10173,20th Century Women,12/28/2016,73,Drama,"In 1979 Santa Barbara, California, Dorothea Fi...","Annette Bening, Dorothea Fields, Lucas Jade Zu...",20th Century Women,Released,English,7000000.0,9.353729e+06,US
10174,Delta Force 2: The Colombian Connection,08/24/1990,54,Action,When DEA agents are taken captive by a ruthles...,"Chuck Norris, Col. Scott McCoy, Billy Drago, R...",Delta Force 2: The Colombian Connection,Released,English,9145817.8,6.698361e+06,US
10175,The Russia House,12/21/1990,61,"Drama, Thriller, Romance","Barley Scott Blair, a Lisbon-based editor of R...","Sean Connery, Bartholomew 'Barley' Scott Blair...",The Russia House,Released,English,21800000.0,2.299799e+07,US
10176,Darkman II: The Return of Durant,07/11/1995,55,"Action, Adventure, Science Fiction, Thriller, ...",Darkman and Durant return and they hate each o...,"Larry Drake, Robert G. Durant, Arnold Vosloo, ...",Darkman II: The Return of Durant,Released,English,116000000.0,4.756613e+08,US
10177,The Swan Princess: A Royal Wedding,07/20/2020,70,"Animation, Family, Fantasy",Princess Odette and Prince Derek are going to ...,"Nina Herzog, Princess Odette (voice), Yuri Low...",The Swan Princess: A Royal Wedding,Released,English,92400000.0,5.394018e+08,GB

#### Loading data from a webpage

Sometimes the data we want to access is stored on the web. Thankfullty, can also use `read_csv` to easily load a csv file directly from a website. We simply need to pass the webpage's URL as the `filepath`.

For instance, the `imdb_movie_info.csv` file is also stored on our course's GitHub page.

* The ordinary csv file can be found here: https://github.com/ntstevens/DATSC101/blob/main/data/imdb_movie_info.csv
* And the "raw" version can be found here: https://raw.githubusercontent.com/ntstevens/DATSC101/refs/heads/main/data/imdb_movie_info.csv

It's the URL for the raw version that we want to use:

In [24]:
pd.read_csv("https://raw.githubusercontent.com/ntstevens/DATSC101/refs/heads/main/data/imdb_movie_info.csv")

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
0,Creed III,03/02/2023,73,"Drama, Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",Creed III,Released,English,75000000.0,2.716167e+08,AU
1,Avatar: The Way of Water,12/15/2022,78,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU
2,The Super Mario Bros. Movie,04/05/2023,76,"Animation, Adventure, Family, Fantasy, Comedy","While working underground to fix a water main,...","Chris Pratt, Mario (voice), Anya Taylor-Joy, P...",The Super Mario Bros. Movie,Released,English,100000000.0,7.244590e+08,AU
3,Mummies,01/05/2023,70,"Animation, Comedy, Family, Adventure, Fantasy","Through a series of unfortunate events, three ...","Óscar Barberán, Thut (voice), Ana Esther Albor...",Momias,Released,"Spanish, Castilian",12300000.0,3.420000e+07,AU
4,Supercell,03/17/2023,61,Action,Good-hearted teenager William always lived in ...,"Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...",Supercell,Released,English,77000000.0,3.409420e+08,US
...,...,...,...,...,...,...,...,...,...,...,...,...
10173,20th Century Women,12/28/2016,73,Drama,"In 1979 Santa Barbara, California, Dorothea Fi...","Annette Bening, Dorothea Fields, Lucas Jade Zu...",20th Century Women,Released,English,7000000.0,9.353729e+06,US
10174,Delta Force 2: The Colombian Connection,08/24/1990,54,Action,When DEA agents are taken captive by a ruthles...,"Chuck Norris, Col. Scott McCoy, Billy Drago, R...",Delta Force 2: The Colombian Connection,Released,English,9145817.8,6.698361e+06,US
10175,The Russia House,12/21/1990,61,"Drama, Thriller, Romance","Barley Scott Blair, a Lisbon-based editor of R...","Sean Connery, Bartholomew 'Barley' Scott Blair...",The Russia House,Released,English,21800000.0,2.299799e+07,US
10176,Darkman II: The Return of Durant,07/11/1995,55,"Action, Adventure, Science Fiction, Thriller, ...",Darkman and Durant return and they hate each o...,"Larry Drake, Robert G. Durant, Arnold Vosloo, ...",Darkman II: The Return of Durant,Released,English,116000000.0,4.756613e+08,US
10177,The Swan Princess: A Royal Wedding,07/20/2020,70,"Animation, Family, Fantasy",Princess Odette and Prince Derek are going to ...,"Nina Herzog, Princess Odette (voice), Yuri Low...",The Swan Princess: A Royal Wedding,Released,English,92400000.0,5.394018e+08,GB

#### What if my data is not in a `csv` file?

Tabular data is not necessarily store in `csv` files. It may also be stored in:

* `.xlsx` files
* `.json` files
* `.txt` files
* ...

But no problem, `pandas` provides functionality for reading in data from many sources. We're only getting started. We'll gain experience loading data from other sources later in the course.

---
---