---
---
# TUTORIAL 3: PPDAC & EXPLORATORY DATA ANALYSIS

In this tutorial, we revisit the IMBD data we briefly looked at in [Tutorial 2](https://github.com/ntstevens/DATSC101/blob/a44f6311f6c1cd4c2e5aa01634fef3fc70a79359/Tutorials/Tutorial%202.ipynb). We will consider attributes of the data, the data collection process, and the sorts of questions we're able to answer. We'll then get started with some preliminary exploratory data analysis.

---
---
## About the Data: IMDb Movie Info

<div style="text-align: center;">
<img src="https://thumb.wikimedia.org/wikipedia/commons/thumb/6/69/IMDB_Logo_2016.svg/1280px-IMDB_Logo_2016.svg.png" alt="PPDAC" width="600"/>
</div>

[Image Source](https://en.wikipedia.org/wiki/IMDb)

In the previous tutorial, we simply read-in the data stored in `imdb_movie_info.csv`, which is available on GitHub [here](https://github.com/ntstevens/DATSC101/blob/a44f6311f6c1cd4c2e5aa01634fef3fc70a79359/data/imdb_movie_info.csv).

Today we'll begin working with it. As we saw, the data set contains information from IMDb (Internet Movie Database) about many movies. An overview of the variables recorded for each movie is provided below.

* `names`: the movie name
* `date_x`: the release of the movie
* `score`: the IMBD score for the movie (multiplied by 10)
* `genre`: the genre(s) of the movie
* `overview`: a summary of the movie
* `crew`: notable cast in the movie
* `orig_title`: the original tile of the movie (often but not always the same as `names`)
* `status`: the production status of the movie (either  `In Production`, `Post Production` or `Released`)
* `orig_lang`: the language the movie was originally released with
* `budget_x`: the budget (in USD) of the movie
* `revenue`: the revenue (in USD) of the movie
* `country`: the country the movie was originally released in

---
---

### PPDAC

#### Before we analyze this data, let's give some thought to the Problem, Plan, and Data.

* What type of data is this?
* What are some questions we _can_ answer with this data?
* What are some questions we _can't_ answer with this data?
* What is a *unit* in this dataset?
* What is the *target population*?
* What is the *response variable* and what are the *explanatory variables*?

---
---

### EDA

#### 1. Load the data.

In [ ]:
import pandas as pd
movies = pd.read_csv('https://raw.githubusercontent.com/ntstevens/DATSC101/a44f6311f6c1cd4c2e5aa01634fef3fc70a79359/data/imdb_movie_info.csv')

#### 2. How many movies are in this dataset?

In [ ]:
movies.shape

(10178, 12)

#### 3. Confirm that the variable names listed above are correct.

In [ ]:
movies.columns

Index(['names', 'date_x', 'score', 'genre', 'overview', 'crew', 'orig_title',
       'status', 'orig_lang', 'budget_x', 'revenue', 'country'],
      dtype='object')

#### 4. Rename `date_x` and `budget_x` to exclude `_x`.

In [ ]:
movies = movies.rename(columns = {"date_x":"date",
                                  "budget_x":"budget"})
movies.columns

Index(['names', 'date', 'score', 'genre', 'overview', 'crew', 'orig_title',
       'status', 'orig_lang', 'budget', 'revenue', 'country'],
      dtype='object')

#### 5. Preview the data using the `df.head()` and `df.tail()` methods.

In [30]:
movies.head(3)

,names,date,score,genre,overview,crew,orig_title,status,orig_lang,budget,revenue,country
0,Creed III,03/02/2023,73,"Drama, Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",Creed III,Released,English,75000000.0,2.716167e+08,AU
1,Avatar: The Way of Water,12/15/2022,78,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU
2,The Super Mario Bros. Movie,04/05/2023,76,"Animation, Adventure, Family, Fantasy, Comedy","While working underground to fix a water main,...","Chris Pratt, Mario (voice), Anya Taylor-Joy, P...",The Super Mario Bros. Movie,Released,English,100000000.0,7.244590e+08,AU

In [31]:
movies.tail(3)

,names,date,score,genre,overview,crew,orig_title,status,orig_lang,budget,revenue,country
10175,The Russia House,12/21/1990,61,"Drama, Thriller, Romance","Barley Scott Blair, a Lisbon-based editor of R...","Sean Connery, Bartholomew 'Barley' Scott Blair...",The Russia House,Released,English,21800000.0,22997992.0,US
10176,Darkman II: The Return of Durant,07/11/1995,55,"Action, Adventure, Science Fiction, Thriller, ...",Darkman and Durant return and they hate each o...,"Larry Drake, Robert G. Durant, Arnold Vosloo, ...",Darkman II: The Return of Durant,Released,English,116000000.0,475661306.0,US
10177,The Swan Princess: A Royal Wedding,07/20/2020,70,"Animation, Family, Fantasy",Princess Odette and Prince Derek are going to ...,"Nina Herzog, Princess Odette (voice), Yuri Low...",The Swan Princess: A Royal Wedding,Released,English,92400000.0,539401838.6,GB

#### 6. Does `crew` seem like an informative name? No? Rename it.

In [32]:
movies = movies.rename(columns = {"crew":"cast"})
movies.columns

Index(['names', 'date', 'score', 'genre', 'overview', 'cast', 'orig_title',
       'status', 'orig_lang', 'budget', 'revenue', 'country'],
      dtype='object')

#### 7. Calculate summary statistics of numeric columns using the `df.describe()` method.

In [ ]:
movies.describe()

              score        budget       revenue
count  10178.000000  1.017800e+04  1.017800e+04
mean      63.497052  6.488238e+07  2.531401e+08
std       13.537012  5.707565e+07  2.777880e+08
min        0.000000  1.000000e+00  0.000000e+00
25%       59.000000  1.500000e+07  2.858898e+07
50%       65.000000  5.000000e+07  1.529349e+08
75%       71.000000  1.050000e+08  4.178021e+08
max      100.000000  4.600000e+08  2.923706e+09

#### 8. Calculate summary statistics of _all_ columns using the `df.describe()` method.

In [ ]:
movies.describe(include = "all")

,names,date,score,genre,overview,crew,orig_title,status,orig_lang,budget,revenue,country
count,10178,10178,10178.000000,10093,10178,10122,10178,10178,10178,1.017800e+04,1.017800e+04,10178
unique,9660,5688,NaN,2303,9905,9927,9736,3,54,NaN,NaN,60
top,Pinocchio,04/07/2023,NaN,Drama,We don't have an overview translated in Englis...,"Scout Taylor-Compton, Laurie Strode, Tyler Man...",Pinocchio,Released,English,NaN,NaN,AU
freq,12,41,NaN,556,89,3,12,10131,7417,NaN,NaN,4885
mean,NaN,NaN,63.497052,NaN,NaN,NaN,NaN,NaN,NaN,6.488238e+07,2.531401e+08,NaN
std,NaN,NaN,13.537012,NaN,NaN,NaN,NaN,NaN,NaN,5.707565e+07,2.777880e+08,NaN
min,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00,0.000000e+00,NaN
25%,NaN,NaN,59.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.500000e+07,2.858898e+07,NaN
50%,NaN,NaN,65.000000,NaN,NaN,NaN,NaN,NaN,NaN,5.000000e+07,1.529349e+08,NaN
75%,NaN,NaN,71.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.050000e+08,4.178021e+08,NaN
max,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,4.600000e+08,2.923706e+09,NaN

#### 9. Find the ten highest-budget movies using the `df.sort_values()` method.

In [ ]:
movies.sort_values(by = "budget", ascending = False).head(10)

,names,date,score,genre,overview,crew,orig_title,status,orig_lang,budget,revenue,country
1,Avatar: The Way of Water,12/15/2022,78,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU
230,Avengers: Endgame,04/24/2019,83,"Adventure, Science Fiction, Action",After the devastating events of Avengers: Infi...,"Robert Downey Jr., Tony Stark / Iron Man, Chri...",Avengers: Endgame,Released,English,400000000.0,2.794732e+09,AU
298,Pirates of the Caribbean: On Stranger Tides,05/19/2011,65,"Adventure, Action, Fantasy",Captain Jack Sparrow crosses paths with a woma...,"Johnny Depp, Jack Sparrow, Penélope Cruz, Ange...",Pirates of the Caribbean: On Stranger Tides,Released,English,379000000.0,1.045714e+09,AU
329,Avengers: Age of Ultron,04/23/2015,73,"Action, Adventure, Science Fiction",When Tony Stark tries to jumpstart a dormant p...,"Robert Downey Jr., Tony Stark / Iron Man, Chri...",Avengers: Age of Ultron,Released,English,365000000.0,1.395317e+09,AU
117,Fast X,05/19/2023,0,"Action, Crime, Thriller",Over many missions and against impossible odds...,"Vin Diesel, Dominic Toretto, Michelle Rodrigue...",Fast X,Post Production,English,340000000.0,0.000000e+00,US
104,Avengers: Infinity War,04/25/2018,83,"Adventure, Action, Science Fiction",As the Avengers and their allies have continue...,"Robert Downey Jr., Tony Stark / Iron Man, Chri...",Avengers: Infinity War,Released,English,300000000.0,2.048360e+09,AU
2351,Spectre,11/12/2015,65,"Action, Adventure, Thriller",A cryptic message from Bond’s past sends him o...,"Daniel Craig, James Bond, Christoph Waltz, Fra...",Spectre,Released,English,300000000.0,8.790773e+08,AU
262,Pirates of the Caribbean: At World's End,05/24/2007,72,"Adventure, Fantasy, Action","Captain Barbossa, long believed to be dead, ha...","Johnny Depp, Jack Sparrow, Orlando Bloom, Will...",Pirates of the Caribbean: At World's End,Released,English,300000000.0,9.610000e+08,AU
812,Justice League,11/16/2017,61,"Action, Adventure, Science Fiction",Fuelled by his restored faith in humanity and ...,"Ben Affleck, Batman / Bruce Wayne, Henry Cavil...",Justice League,Released,English,300000000.0,6.559452e+08,AU
1546,Indiana Jones and the Dial of Destiny,06/30/2023,0,"Adventure, Action","Finding himself in a new era, approaching reti...","Harrison Ford, Indiana Jones, Phoebe Waller-Br...",Indiana Jones and the Dial of Destiny,Post Production,English,294700000.0,1.240262e+06,US

#### 10. Find the five highest-revenue movies using the `df.sort_values()` method.

In [ ]:
movies.sort_values(by = "revenue", ascending = False).head(5)

,names,date,score,genre,overview,crew,orig_title,status,orig_lang,budget,revenue,country
68,Avatar,12/17/2009,76,"Action, Adventure, Fantasy, Science Fiction","In the 22nd century, a paraplegic Marine is di...","Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",Avatar,Released,English,237000000.0,2.923706e+09,AU
230,Avengers: Endgame,04/24/2019,83,"Adventure, Science Fiction, Action",After the devastating events of Avengers: Infi...,"Robert Downey Jr., Tony Stark / Iron Man, Chri...",Avengers: Endgame,Released,English,400000000.0,2.794732e+09,AU
1,Avatar: The Way of Water,12/15/2022,78,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU
309,Titanic,12/18/1997,79,"Drama, Romance",101-year-old Rose DeWitt Bukater tells the sto...,"Leonardo DiCaprio, Jack Dawson, Kate Winslet, ...",Titanic,Released,English,200000000.0,2.222986e+09,AU
6670,Titanic,04/11/1953,66,"Drama, Romance","Unhappily married, Julia Sturges decides to go...","Clifton Webb, Richard Ward Sturges, Barbara St...",Titanic,Released,English,200000000.0,2.222986e+09,US

#### 11. Does anything seem amiss with the previous result? What does that say about data quality?